// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejmlhoxhiupdobdlzjnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbWxob3hoaXVwZG9iZGx6am5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMjU5OTIsImV4cCI6MjA5MTgwMTk5Mn0.Mssrl4bVxE_KGj3Rqv7tGIBLafhP9UokBVHQU2PsFEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});